name:                haskell-evm
version:             0.1.0
github:              "reach-sh/haskell-evm"
license:             Apache-2.0
author:              "Reach"
maintainer:          "jay@reach.sh"
copyright:           "2019 Reach"
description:         Please visit the GitHub repository <https://github.com/reach-sh/haskell-evm#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- hspec
- smallcheck
- hspec-smallcheck

ghc-options:
- -Wall
- -Werror
- -O2

library:
  source-dirs: src

tests:
  haskell-evm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-evm
